USE master

GO

DROP DATABASE IF EXISTS QLNV

CREATE DATABASE QLNV

GO

USE QLNV

DROP TABLE IF EXISTS STAFF

DROP TABLE IF EXISTS DEPARTMENT

CREATE TABLE DEPARTMENT(
	id				VARCHAR(10)		NOT NULL,
	department		NVARCHAR(255)	NOT NULL,

	CONSTRAINT PK_DEPARTMENT		PRIMARY KEY (id),
)

CREATE TABLE STAFF(
	id				VARCHAR(10)		NOT NULL,
	department_id	VARCHAR(10)		NOT NULL,
	first_name		NVARCHAR(50)	NOT NULL,
	last_name		NVARCHAR(50)	NOT NULL,
	full_name		NVARCHAR(100)	NOT NULL,
	gender			NVARCHAR(10)	NOT NULL,
	birthday		DATETIME		NOT NULL,
	home			NVARCHAR(255)	NOT NULL,

	CONSTRAINT PK_STAFF			PRIMARY KEY (id),
	CONSTRAINT FK_DEPARTMENT	FOREIGN KEY (department_id) REFERENCES DEPARTMENT(id)
)

